- src/collector.ts
- src/server.ts
Provides support for python ecosystem through requirements.txt, like we show recommendations currently for pom.xml.
> support for python ecosystem through requirements.txt

- src/json.ts
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>
> fixes devstudio issue with lsp, with typed binding

- package.json
- src/server.ts
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>
> updates package

- package.json
- src/server.ts
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>
> handles host not found for lsp

- package.json
- src/server.ts
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>
> updates error message , version

- .gitignore
- cico_build_deploy.sh
- cico_release.sh
- cico_run_tests.sh
- cico_setup.sh
- package-lock.json
- package.json
> feat(cicd): Files to bring in cicd process

- cico_release.sh
Create a merge PR on the vscode-extension repo for the new version released.
Depends on :- https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/163
> fix(cd): create merge PR on vscode

- cico_release.sh
update the git tags sort script which is compatible for git version < 2.x
> fix(git-sort): updated the git tags sort command

- cico_release.sh
Test if fabric8cd is able to create a PR on fabric8-analytics-vscode-extension to update the LSP Server version
> fix(test): test the create pr script

- cico_release.sh
Script to create PR in rh-che to automate CD process
> fix(CD): script to raise PR in rh-che

- cico_release.sh
> fix(CD): fix script to raise  PR in rh-che

- cico_release.sh
Fix the script to replace the version to the latest.
> fix(script): fix CD script

- cico_release.sh
correct the download path for `.tar` file
> fix(script): fix the download path for asset

- README.md
This is a PR to test if `.tar` file is uploaded in the release
> fix(test): test commit to see if .tar is uploaded

- README.md
> fix(test-release): Test Release

- src/server.ts
Validation for version: 
- Checks for starts with alphanumeric
- shouldn't end with special characters
> Add java dependency version validation

- README.md
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> fix(readme): fix presentation of readme

- .gitignore
- README.md
- src/server.ts
enables code-action and updates notification messages along with readme
> fix(code-action): enables code-action and updates notification messages

- src/collector.ts
- src/server.ts
-  LS support for requirements.txt
> fix(pypi): LS support for requirements.txt

- src/server.ts
- Club component analyses call to make ten requests in a single call.
Tracks : https://openshift.io/openshiftio/Openshift_io/plan/detail/1195
> fix(perf): club component analysis calls to reduce number of calls

- src/consumers.ts
- src/server.ts
Fixes #95
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
> fix(code-action): code actions now returns code actions instead of commands

- src/server.ts
Tracks https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/issues/99
> fix(comp): updates Post call to get

- package.json
- src/json.ts
- src/server.ts
This is a LSP side fix for https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/287.
> fix(deps): Update dependencies to latest to support webpacking

- README.md
I am adding the QA checks and then will add this repository to the QA dashboard Meanwhile have just embedded the Build Status in Readme
> Embedded the Build Status for the Repository in Readme

- src/consumers.ts
- src/server.ts
1. Parse the new API-v2 response for Component Analysis.
2. Modification of Diagnostic object. Using Diagnostic.Code to provide URI objects.
3. Provide 'QuickFix' if recommendation version is available. 
4. Update the summarised message for VS-Code Extension Notification with total number of vulnerability counts of each type of Vulnerabilities.
> Component Analysis UI changes for api-V2

- src/consumers.ts
- src/server.ts
Reverts fabric8-analytics/fabric8-analytics-lsp-server#116
> Revert "Component Analysis UI changes for api-V2"

- src/consumers.ts
- src/server.ts
feat(v2): Component Analysis UI changes for V2 API
> feat(v2): Component Analysis changes for V2 API

- src/consumers.ts
fix(v2): Update diagnostic.source with Snyk attribution and remove Diagnostic Code.
> fix(v2): Update diagnostic.source with Snyk attribution

- src/consumers.ts
fix(v2): Update diagnostic.source with snyk attribution and remove Diagnostic.code (#119)
> fix(v2): Update diagnostic.source with snyk attribution and remove Diagnostic.code (#119)

- src/server.ts
Update notification message:
- Remove "runtime" from notification message.
> fix(v2): Update notification message

- .gitignore
- cico_release.sh
- cico_setup.sh
- package-lock.json
- package.json
* Updated semantic-release to latest
* Added package-lock.json
> fix(semantic-release): Update semantic-release to latest

- package.json
- src/consumers.ts
- src/server.ts
- tsconfig.json
**Update component-analysis get call to post call**: 
- using batch of 10 dependencies in each call
- send UUID via the header in post call for anonymous user management/tracking
> fix(request): Use component-analysis batch API

- src/consumers.ts
- test/consumer.test.ts
E.g.: 
```
lodash: 4.17.4
Known security vulnerability: 4
Security advisory: 1
Exploits: 2
Highest severity: high
Recommendation: use version 4.17.20.
```
> fix: Update diagnostic message

- README.md
- src/server.ts
> fix: Ignore uuid header if UUID env is empty or not set

- src/collector.ts
Jira ticket :: https://issues.redhat.com/browse/APPAI-1650
> fix: [APPAI-1650][Golang] Use SHELL environment while executing go cmd

- src/server.ts
uri will be helpful in identifying the context associated with the notification.
> fix: Add uri to ca completion/err notification payload

- .github/workflows/ci-build.yml
- .gitignore
- package-lock.json
- package.json
There is an issue with [indirect dependency](https://github.com/SAP/chevrotain/pull/1269) of @xml-tools/parser which is causing [runtime error](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/481) with webpack minification.
Refer https://github.com/SAP/xml-tools/pull/282
> fix: upgrade @xml-tools/parser to 1.0.9

- package-lock.json
- package.json
- src/server.ts
The usage of winston is not really helping in anyways, removing it as users started complaining.
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/496
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
> fix: Remove winston package usage as it is not really used

- .github/workflows/ci-build.yml
- .github/workflows/conventional-commit-msg.yml
Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>
> chore: adopt conventional commits

- package-lock.json
- package.json
- src/server.ts
Supporting RHDA_TOKEN and RHDA_SOURCE
> chore: update to exhort-javascript-api version to 0.0.2-ea.32

- package-lock.json
- package.json
Fix python exhortignore in Exhor Javascript API
> fix: upgrade Exhort Javascript API version

- package-lock.json
- package.json
- src/componentAnalysis.ts
- src/diagnosticsHandler.ts
Upgrade Exhort Javascript API version to 0.1.1-ea.2
> chore: upgrade Exhort Javascript API version

- src/config.ts
- test/config.test.ts
Updated configuration names in extension settings to redHatDependencyAnalytics.<executable>.executable.path format for all supported executable paths in the extension
> chore: update extension settings

- src/codeActionHandler.ts
- src/diagnosticsHandler.ts
- src/server.ts
- test/codeActionHandler.test.ts
- test/vulnerability.test.ts
> fix: upgrade codeActionsMap to support multiple open documents accurately

- src/codeActionHandler.ts
- src/config.ts
- src/server.ts
- test/codeActionHandler.test.ts
- test/config.test.ts
RHDA VSCode Extension is Migrating to VSCode Secret Storage to enhance security by storing tokens in VSCode's built-in Secret Storage.
Code refactored to accommodate the new token-saving mechanism.
> feat: receive updated Snyk token by notification from clients VSCode Secret Storage

- src/utils.ts
- test/utils.test.ts
fix: https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/681
> fix: remove / from Windows decoded URI path

- README.md
- src/fileHandler.ts
- src/providers/docker.ts
- test/codeActionHandler.test.ts
- test/imageAnalysis/collector.test.ts
- test/providers/docker.test.ts
RHDA Image Analysis now providing analysis for Containerfiles
> chore: added Containerfile support

- package-lock.json
- package.json
- src/codeActionHandler.ts
- src/constants.ts
- src/dependencyAnalysis/collector.ts
- src/dependencyAnalysis/diagnostics.ts
- src/diagnosticsPipeline.ts
- src/fileHandler.ts
- src/providers/build.gradle.ts
- src/providers/go.mod.ts
- src/providers/package.json.ts
- src/providers/pom.xml.ts
- src/providers/requirements.txt.ts
- test/codeActionHandler.test.ts
- test/dependencyAnalysis/collector.test.ts
- test/providers/build.gradle.test.ts
RHDA LSP server now supporting Gradle ecosystem.
The Component Analysis feature for build.gradle dependency manifest is now available.
> feat: gradle support

- package-lock.json
- package.json
- src/config.ts
- src/dependencyAnalysis/analysis.ts
- test/config.test.ts
Fix https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/766 (LSP Sever part)
> feat: add support for yarn

- src/config.ts
- src/dependencyAnalysis/analysis.ts
- test/config.test.ts
Fix https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/765 (LSP Server side)
> feat: add support for pnpm

- src/config.ts
- src/dependencyAnalysis/analysis.ts
- src/server.ts
- test/config.test.ts
LSP Server side of https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/712
> feat: support configure a proxy url

- package-lock.json
- package.json
Include https://github.com/trustification/exhort-javascript-api/pull/206
> chore(deps): update js api to ea.74

- package-lock.json
- src/dependencyAnalysis/analysis.ts
- src/imageAnalysis/analysis.ts
- src/imageAnalysis/collector.ts
- src/imageAnalysis/diagnostics.ts
- test/imageAnalysis/collector.test.ts
LSP side of https://github.com/trustification/exhort-javascript-api/pull/202
> feat: implement OCI image analysis natively instead of via java API adapter

- package-lock.json
- package.json
> chore: upgrade to js 0.2.3
