- README.md
- src/server.ts
Use environment variable to configure recommender API url
Fix #1
> Use env variable to setup recommender API url

- src/server.ts
Currently bayesian.log is created in current working directory (i.e. `/projects/` for Che workspaces). 
For consistency with other workspace agents ls-bayesian should log in it's own directory (`/home/user/che`).
> Log in folder /home/user/che/ls-bayesian

- src/server.ts
For now, it logs in /home/user/che but as part of logging to a persistent volume, we may log to the `/workspace-logs` folder which is backed by the persistent volume.
warning : it requires merged PR https://github.com/redhat-developer/rh-che/pull/199
https://github.com/redhat-developer/rh-che/issues/145
@l0rd
> Use a path that is storing on a persistent volume

- package.json
- removed `semantic-release post` command as this will be a modified as per the requirement to include the .tar file.
> fix(pr-merge-build): ignoring semantic-release post command for now

- cico_run_tests.sh
- cico_setup.sh
- package.json
- src/collector.ts
- test/mocha.opts
- test/pypi.collector.test.ts
- tsconfig.json
It fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/315.
Empty lines(with and without #) are also counted as dependencies.
If parsed package name is empty, ignore it.
I also did some refactoring to use JS map/reduce for a nice looking code :)
Chai, mocha based unit tests has been added newly. Also added [nyc](https://istanbul.js.org/) based code coverage and modified code has been covered 100%.
Follow the below steps to test this change along with fabric8-analytics-vscode-extension,
```
git clone https://github.com/fabric8-analytics/fabric8-analytics-lsp-server.git
cd fabric8-analytics-lsp-server
git fetch https://github.com/arajkumar/fabric8-analytics-lsp-server.git fix-incorrect-dep-count-pypi
git checkout FETCH_HEAD
npm install && npm run build
git …
```
> fix(pypi): Dependency count shown in stack analysis report is incorrect

- package.json
- src/collector.ts
- src/json.ts
- src/server.ts
fix(stream-json): Move to 0.x, new release doesn't pass position info
Refactor send diag message to avoid duplicate codes
Issue: https://jira.coreos.com/browse/APPAI-1060
https://gist.github.com/samuzzal-choudhury/618a50bba5f3c1f829d6abe8dc6057ed
There are few dependencies are in the form of `mainpkg/subpkg` in the above manifest file(e.g. `@angular/animations`),  which causes `subpkg` being interpreted as version. 
URI encoding the dependency name.
> fix(uri-char): URI encode the args which is passed for component anaysis

- src/collector.ts
- test/maven.collector.test.ts
Jira issue: https://issues.redhat.com/browse/APPAI-1397 
With reference to : https://issues.redhat.com/browse/APPAI-1288
Updating scope parsing for maven dependencies, to exclude dependencies with test scope, and also include dependencies with provided and system scopes in LSP for Component Analysis. (Reference: https://maven.apache.org/pom.html#dependencies )
> fix(v2): Update maven dependency parsing to exclude dependencies with test scope.

- cico_release.sh
Skipping this until PR creation stabilises.
> fix(pr): Don't create PR to upgrade lsp in vscode extension repo

- cico_release.sh
- package.json
This fixes the below error,
[semantic-release] › ℹ  This test run was triggered on the branch origin/master, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
> fix: Strip remote name from GIT_BRANCH env var

- src/consumers.ts
- src/server.ts
Consume response for Registered Users with exploitable vulnerability count:
E.g.:
- Notification Message: 
`Scanned 27 dependencies, flagged 19 Known Security Vulnerabilities and 7 Security Advisories with 8 Exploitable Vulnerabilities along with quick fixes.`
- Diagnostic Message:
`lodash - 4.17.4 has 4 known security vulnerability and 1 security advisory with 2 exploitable vulnerabilities. Recommendation: use version 4.17.20.`
> fix(v2): Consume response for Registered Users with exploitable vulnerability count

- src/consumers.ts
- test/consumer.test.ts
fix(v2): Show quick-fix for security-advisories only to registered users, for dependency has only security-advisories.
> fix(v2): Show quick-fix for security-advisories only to registered users

- src/collector.ts
- test/gomod.collector.test.ts
Resolving below jira issue and fixing version string parsing using regex.
https://issues.redhat.com/browse/APPAI-1484
> fix: Support for single line require and version string parsing using regex

- src/consumers.ts
- src/server.ts
This PR enables CodeActions to trigger full stack report in the context of each diagnostics. 
Newly added CodeAction would be enabled based on the env variable(PROVIDE_FULLSTACK_ACTION==“true”) so that it shall be enabled only for VSCode.
https://issues.redhat.com/browse/APPAI-1590
> fix: Add code action to trigger full stack report

- src/collector.ts
- src/server.ts
LPS should check for go executable path and provide proper error message to VS Code in case of error. This error can happen when LSP server process is not having proper PATH value that contains go executable path.
Fixes jira ticket :: https://issues.redhat.com/browse/APPAI-1638
Error message in case go executable is not found:
Error message in case `go list` command fails:
> fix: [APPAI-1638] Check for go executable and provide proper error message

- src/collector.ts
- src/utils.ts
- test/gomod.collector.test.ts
CA might add/update dependencies in go.mod. Adding -mod=readonly during go list command shall avoid go.mod modification.
Fixes jira ticket :: https://issues.redhat.com/browse/APPAI-1643
> fix: [APPAI-1643][Golang]CA might add/update dependencies in go.mod

- src/collector.ts
- test/gomod.collector.test.ts
This implements the support for indirect modules present in go.mod.
Jira ticket :: https://issues.redhat.com/browse/APPAI-1641
> fix: [APPAI-1641] Consider direct and indirect modules in go.mod file

- src/collector.ts
- test/gomod.collector.test.ts
Golang manifest file go.mod has "replace" directive which needs to be considered while generating CA batch request.
1. Manifest go.mod shall not highlight the vulnerability of actual module in "require" section if there is replace statement for the same module.
2. "replace" section, destination module should be highlighted in case of vulnerability for that module or any packages of the module.
> fix: [APPAI-1618] Handle replace directive from go.mod

- src/server.ts
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/458
Using `connection.log.error` automatically shows output window of LSP. Switch to `connection.log.warn` instead.
> fix: Use warn level instead error when logging

- src/server.ts
Upon CA trigger there are cases when in golang can fail to generate data using go list command. In this case plugin still highlights existing go.mod with diagnostic which are not appropriated for modified content. Solution was to clean all diagnostic messages upon error.
Jira ticket :: https://issues.redhat.com/browse/APPAI-1657
> fix: [APPAI-1655] Clearing all diagnostic message in case of error for golang

- src/server.ts
This fix would help in enhancing the user experience by providing status message in VSCode.
Changes are backward compatible and doesn't affect the existing clients.
Refer https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/459
> fix: Add more stat to notification payload

- src/server.ts
On LSP we have below code for onCodeAction and onDidChangeTextDocument
```
connection.onCodeAction((params, token): CodeAction[] => {
clearTimeout(checkDelay);
let codeActions: CodeAction[] = [];
connection.onDidChangeTextDocument((params) => {
/* Update internal state for code lenses */
server.files.file_data[params.textDocument.uri] = params.contentChanges[0].text;
clearTimeout(checkDelay);
checkDelay = setTimeout(() => {
server.handle_file_event(params.textDocument.uri, server.files.file_data[params.textDocument.uri])
}, 500)
```
Upon document change, onDidChange gets fired and it starts timer of 500 ms to trigger CA, but before this timer is fired I see onCodeAction() callback, which clears this timer as shown above. I think clearTimeout() from onCodeAction() should not be present. …
> fix: [APPAI-1656] Don't clear request aggregation timer on CodeAction request

- src/server.ts
1. Create the requirements.txt with following contents,
```
flask == 0.12
```
2. Empty the requirements.txt by selecting all deps in one go
Not all diagnostics are not cleared
No diagnostics should be shown
Empty manifest/manifest with invalid dependency is not triggering CA api call
Clear diagnostics on every manifest change
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/465, https://issues.redhat.com/browse/APPAI-1676
> fix: Clear diagnostics before generating new set of diagnostics

- .github/workflows/release.yml
- package-lock.json
- package.json
- release.config.js
This PR bundles nodejs runtime along with lsp for linux, macos and windows 64 bit platforms to eliminate nodejs dependency on intellij and similar platforms.
Also this moves npm package publishing to GH Actions and removes dependency on centos ci.
Note: Other platforms and CPU shall be enabled based on request . e.g BSD, ARM,.
> chore: Bundle nodejs runtime using pkg

- release.config.js
- src/server.ts
There is no use to send diagnostics on every vulnerability from sync loop. It should be sent per batch.
Also fixed release binary linux artefact label.
> fix: Avoid excessive sendDiagnostic calls

- src/collector/package.json.ts
- test/collector/go.mod.test.ts
- test/collector/package.json.test.ts
- test/collector/requirements.txt.test.ts
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/493
> fix: handle empty cases for all manifests

- src/collector/go.mod.ts
- src/utils.ts
- test/collector/go.mod.test.ts
PR to resolve two issue with windows CA golang failure as below:
1. Current working directory was having invalid folder path.
2. Go list command to get list of imports does not work  as expected on linux/darwin.
Jira ticket :: https://issues.redhat.com/browse/APPAI-1837
Modification tested on Linux, Windows and Mac.
> fix: [APPAI-1837] [Golang] CA trigger fails on windows

- src/collector/package.json.ts
- test/collector/package.json.test.ts
It doesn't make sense to throw syntax errors.
Fixes https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/513
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
> fix: mute syntax errors from package.json

- src/server.ts
Adding these properties would help in sending telemetry event from extension without too much of changes.
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
> fix: add cache properties to ca notification payload

- package-lock.json
- package.json
- src/collector.ts
- src/providers/go.mod.ts
- src/server.ts
- test/collector.test.ts
- test/providers/go.mod.test.ts
1. Updated Exhort Javascript API version to 0.0.2-ea.29
2. modified go.mod collector to ignore excluded dependencies
> chore: updated Exhort JS API version and modified go.mod collector

- src/providers/pom.xml.ts
- src/server.ts
- test/aggregators.test.ts
- test/providers/pom.xml.test.ts
- test/vulnerability.test.ts
Remove outdated effective pom generation in client for maven dependency manifest (pom.xml).
Refactored pom.xml content collection module.
Updated unit tests.
> chore: remove effective-pom generation

- package-lock.json
- src/config.ts
- src/server.ts
Passed the TELEMETRY_ID environment variable from VSCode extension (where is it generated) to LSP Server.
Included TELEMETRY_ID as RHDA_TOKEN environment variable in options passed to Exhort JS API component analysis request.
> feat: add RHDA_TOKEN param to Exhort JS API request

- package-lock.json
- package.json
- src/config.ts
- src/providers/requirements.txt.ts
- test/providers/requirements.txt.test.ts
1. Convert python package name key value to lowercase to recognize vulnerabilities received by Exhort
2. Upgrade Exhort JavaScript API version to 0.0.2-ea.46
> fix: python package inclusion

- src/codeActionHandler.ts
- src/diagnosticsHandler.ts
1. Added Red Hat GA repository recommendation to be recommended on remediation as well.
2. fixed duplicate recommendation on quickfix bug
> chore: trusted content support enhancements and fixes

- src/config.ts
- src/diagnosticsHandler.ts
- src/vulnerability.ts
- test/vulnerability.test.ts
Added vulnerability alert severity setting which will allow the user to choose to receive inline dependency vulnerability alerts at Error or Warning level.  
Solution to enhancement issue https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/597
> feat: add vulnerability alert severity setting

- package-lock.json
- package.json
- src/codeActionHandler.ts
- src/componentAnalysis.ts
- src/config.ts
- src/diagnosticsHandler.ts
- src/server.ts
- src/utils.ts
- src/vulnerability.ts
- test/codeActionHandler.test.ts
- test/config.test.ts
- test/utils.test.ts
- test/vulnerability.test.ts
Handles issues and enhancement requests reported by users
> chore: issue handling

- package-lock.json
- package.json
- src/constants.ts
- src/server.ts
- src/vulnerability.ts
- test/providers/pom.xml.test.ts
1.  Fixed the "source" attribute, "Red Hat Dependency Analytics Plugin", in Diagnostics which has been obscured from view in the "View Problem" panel due to VScode  "View Problem" panel format.
2. Disabled Component Analysis trigger for text document edits due to the inability to maintain compatibility with newer features introduced in RHDA version 0.9.2
> fix: view problem panel and ca triggers

- src/config.ts
- src/imageAnalysis/analysis.ts
- test/config.test.ts
removed image scanning settings:
EXHORT_SYFT_IMAGE_SOURCE
EXHORT_IMAGE_SERVICE_ENDPOINT
EXHORT_IMAGE_OS
EXHORT_IMAGE_ARCH
EXHORT_IMAGE_VARIANT
> chore: remove redundant image scanning settings

- package-lock.json
- src/providers/build.gradle.ts
- test/providers/build.gradle.test.ts
Bug: Gradle dependency ref was not matched with corresponding dependency line in manifest when line version is set using an argument. 
Fix: argument translated to actual version value to allow matching
> fix: version detection when using arguments

- package-lock.json
- package.json
- src/providers/build.gradle.ts
Upgraded to JS API version that provides a fix to respect all non-test gradle configuration types and respect spaces in paths passed in settings.
mocha and nyc libraries were updated to their latest versions.
Lastly the argument replacement method in gradle has been upgraded to use regex.
> chore: upgrade JS API version

- .github/workflows/ci.yml
- .github/workflows/release.yml
- package-lock.json
- package.json
- src/dependencyAnalysis/analysis.ts
- src/dependencyAnalysis/diagnostics.ts
Required by https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/757 and https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/264. Primarily includes the changes from https://github.com/trustification/exhort-javascript-api/releases/tag/v0.1.1-ea.52
> chore: upgrade exhort-javsacript-api version

- src/config.ts
- src/dependencyAnalysis/analysis.ts
- src/server.ts
- test/config.test.ts
LSP-side of https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/pull/757. Must duplicate a tiny bit of logic in deriving the exhort config value due to the LSP server receiving configuration both in the initial environment variables (set by the logic on the editors' side) and receiving the raw configuration as well per the protocol (where we need to duplicate the aforementioned logic)
Depends on https://github.com/trustification/exhort-javascript-api/pull/170
> feat: support preferring mvnw
